### ISSUE TITLE
Devhub snap app won't start

### ISSUE THREAD

**Issue by iangabrielsanchez** [devhubapp/devhub#164]
It won't start when I open it normally but I'm getting this when I try to run devhub from the terminal:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EPERM: operation not permitted, chown '/home/ian/snap/devhub/x1/.config/devhub/config.json.717586174'
    at Object.chownSync (fs.js:1142:3)
    at Function.writeFileSync [as sync] (/snap/devhub/x1/resources/app.asar/node_modules/write-file-atomic/index.js:196:27)
    at ElectronStore.set store [as store] (/snap/devhub/x1/resources/app.asar/node_modules/conf/index.js:277:19)
    at ElectronStore.set (/snap/devhub/x1/resources/app.asar/node_modules/conf/index.js:152:14)
    at init (/snap/devhub/x1/resources/app.asar/dist/index.js:36:22)
    at Object.<anonymous> (/snap/devhub/x1/resources/app.asar/dist/index.js:105:1)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
```

**Comment by brunolemos** [comment]
What commands are you trying to run?

Try `yarn && yarn dev:web`

**Comment by iangabrielsanchez** [comment]
Only on the official production build. I used this snap file:
https://github.com/devhubapp/devhub/releases/download/v0.93.0/devhub_0.93.0_amd64.snap

**Comment by iangabrielsanchez** [comment]
> What commands are you trying to run?

I was just trying to launch the app

**Comment by brunolemos** [comment]
How about the AppImage one?

**Comment by brunolemos** [comment]
Caused by:
- https://github.com/anujdatar/onenote-desktop/issues/7#
- https://github.com/npm/write-file-atomic/pull/51

**Comment by brunolemos** [comment]
We've been using only .AppImage, not sure if there's any benefit from re-adding .snap as well
