### ISSUE TITLE
Initial Installation

### ISSUE THREAD

**Issue by kawara417** [devhubapp/devhub#225]
During pod install (following commands from [CONTRIBUTING.md](https://github.com/devhubapp/devhub/blob/master/CONTRIBUTING.md) ), I get this error:
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/kawara/Desktop/projects/devhub/packages/mobile/node_modules/react-native/third-party-podspecs/Folly.podspec

What is the best way to resolve this? I've noticed also that this directory has a RCT-Folly.podspec, but not a Folly.podspec. Report below for more details:

### Command

```
/Users/kawara/.gem/ruby/2.6.0/bin/pod install
```

### Report

* What did you do?

I've followed these commands from [CONTRIBUTING.md](https://github.com/devhubapp/devhub/blob/master/CONTRIBUTING.md):

git clone git@github.com:devhubapp/devhub.git
yarn
cd packages/mobile/ios && pod install && cd -
yarn dev

* What did you expect to happen?

The pods to be installed successfully.

* What happened instead?

Following pod install, I received this error:
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/kawara/Desktop/projects/devhub/packages/mobile/node_modules/react-native/third-party-podspecs/Folly.podspec

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 6452530cc3005267a1c5203edac937bd5789c843

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
load 'remove_unsupported_libraries.rb'

require_relative '../../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'devhub' do
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

  pre_install do |installer|
    codegen_pre_install(installer, :path => config[:reactNativePath])
  end

  # Fix macOS Catalyst Support
  def catalyst_unsupported_pods
      ['FlipperKit', 'Firebase', 'RNFBAnalytics', 'RNFBApp']
  end

  def catalyst_supported_pods
      ['React']
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!('Flipper' => '0.68.0')
  post_install do |installer|
    flipper_post_install(installer)

    # $verbose = true
    installer.configure_support_catalyst(catalyst_supported_pods, catalyst_unsupported_pods)
  end
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/kawara/Desktop/projects/devhub/packages/mobile/node_modules/react-native/third-party-podspecs/Folly.podspec
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:37:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:37:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:37:in `open'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/external_sources/podspec_source.rb:19:in `block in fetch'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/external_sources/podspec_source.rb:11:in `fetch'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:989:in `fetch_external_source'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:968:in `block (2 levels) in fetch_external_sources'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:967:in `each'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:967:in `block in fetch_external_sources'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:966:in `fetch_external_sources'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/kawara/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/kawara/.gem/ruby/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/kawara/.gem/ruby/2.6.0/bin/pod:23:in `load'
/Users/kawara/.gem/ruby/2.6.0/bin/pod:23:in `<main>'
```

**Comment by hunglmtb** [comment]
seem to be parameter `path` of `use_react_native` in `Podfile` not match in your workspace
change  `use_react_native!(:path => "../../../node_modules/react-native")` in `Podfile` work for me
